import Code.Simulations.SimulationHelper as sim

def setup(PARTICLES, KINETIC_OPERATOR, FRAME_SIZE, NUM_FRAMES, Lx,  Ly, Lz, 
			BATCH, RUN, DEVICES, INIT, MODEL, EXP_KWARGS, POTENTIAL, POTENTIAL_KWARGS,
			VISUALIZATION, VIS_KWARGS, MEASUREMENT, MEASUREMENT_KWARGS,
			RUN_TYPE, OVERWRITE = False):
	sim.set_size(Lx, Ly, Lz, PARTICLES, DEVICES) 
	sim.set_experiment(MODEL, KINETIC_OPERATOR, INIT, POTENTIAL, MEASUREMENT, EXP_KWARGS, POTENTIAL_KWARGS, MEASUREMENT_KWARGS, VIS_KWARGS)
	sim.set_runtime(FRAME_SIZE, NUM_FRAMES)
	if RUN_TYPE == 'vis':
		VIS_ONLY = True
	else:
		VIS_ONLY = False
	meta_data = sim.set_directory(BATCH, RUN, VISUALIZATION, VIS_ONLY, OVERWRITE)
	return meta_data